
GMAIL_USERNAME: Collin.Thomas.Schneider@gmail.com
GMAIL_PASSWORD: Thomas34?

STRIPE_PUBLIC_TOKEN: 'pk_test_BnTh2K2CSof6rh1MFjqlMFla'
STRIPE_SECRET_TOKEN: 'sk_test_uQFhbzVPXCNfYt8RWMeCHZTl'

OMNI_AUTH_KEY_1: '1538519413114703'
OMNI_AUTH_KEY_2: 'b62ea4f602ec1ef0111b36e412fbf95d'

GMAIL_USERNAME: Collin.Thomas.Schneider@gmail.com
GMAIL_PASSWORD: Thomas34?
